# Data structures

In [1]:
x=2
x

2

In [2]:
type(x)

int

In [3]:
y=4.6
print(y)
type(y)

4.6


float

In [4]:
x,y

(2, 4.6)

In [5]:
x,y,z=[1,2,3],(2,'yes.1+3j'),{1,2,3}

In [6]:
print(x)
type(x)

[1, 2, 3]


list

In [7]:
print(y)
type(y)

(2, 'yes.1+3j')


tuple

In [8]:
print(z)
type(z)

{1, 2, 3}


set

In [9]:
bin(25)

'0b11001'

In [10]:
0b11001

25

In [11]:
oct(25)

'0o31'

In [12]:
0o31

25

In [13]:
print(x,y)

[1, 2, 3] (2, 'yes.1+3j')


In [14]:
type(x)

list

In [15]:
z='hello'
z

'hello'

In [16]:
z

'hello'

In [17]:
z1='hi'
print(z1)
type(z1)

hi


str

In [18]:
g=True
print(g)
type(g)

True


bool

In [19]:
m1=True+True
m1

2

In [20]:
i=False
i

False

In [21]:
a2=46
b2=56
print(a2,b2)

46 56


In [22]:
a=10
b=20

In [23]:
c=a+b
print(c)

30


In [24]:
d=b/a
print(d)

2.0


In [25]:
e=a*b
e

200

In [26]:
f=b-a
f

10

In [27]:
print(c)
print(d)
print(e)
print(f)

30
2.0
200
10


In [28]:
a1=10
b1=20

In [29]:
a1==b1

False

In [30]:
a1=b1
a1==b1

True

In [31]:
b1=30

In [32]:
a1 !=30

True

In [33]:
int(a1)

20

In [34]:
a1=15
b1=20


In [35]:
a1==b1

False

In [36]:
not(a1)

False

In [37]:
import math

In [38]:
math.sqrt(25)

5.0

In [39]:
ma=round(math.sqrt(25))
ma

5

In [40]:
a=10
math.sqrt(a)

3.1622776601683795

In [41]:
round(math.sqrt(a))

3

In [42]:
greeting='hello'

In [43]:
name='army'

In [44]:
message=greeting + name
message

'helloarmy'

In [45]:
name=' data scientist'

In [46]:
message=greeting + name
message

'hello data scientist'

In [47]:
4<=5

True

In [48]:
10>100

False

In [49]:
10>=100

False

In [50]:
result =4<5
result

True

In [51]:
type(result)

bool

In [52]:
result=5>1
result

True

In [53]:
result1=not(result)
result1

False

In [54]:
result2= not(5>1)
result2

False

In [55]:
result3 = 4<5
result3

True

In [56]:
result

True

In [57]:
result2

False

In [58]:
result3

True

In [59]:
result or result2 or result3

True

In [60]:
result or result3 or result2

True

In [61]:
result and result3 or result2

True

In [62]:
num=12
while num <11:
    print(num)
    num=num+1
print('end of the program')    

end of the program


In [63]:
count=14
while count<=20:
    print(count)
    count=count+1
print('End of the Program')    

14
15
16
17
18
19
20
End of the Program


# for loop

In [64]:
for i in  range (10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [65]:
for v in range (5):
    print("HELLO",v)

HELLO 0
HELLO 1
HELLO 2
HELLO 3
HELLO 4


In [66]:
mylist = ['i',1,1.34,1+23j]
for j in mylist:
    print(j)

i
1
1.34
(1+23j)


In [67]:
list1=[10,100,1000,10000]
list1[:]

[10, 100, 1000, 10000]

In [68]:
list1[::-1]

[10000, 1000, 100, 10]

In [69]:
list1

[10, 100, 1000, 10000]

In [70]:
list1[::-2]

[10000, 100]

In [71]:
list1[-2::]

[1000, 10000]

In [72]:
list1

[10, 100, 1000, 10000]

In [73]:
list1[4]

IndexError: list index out of range

In [ ]:
list1

In [ ]:
for j in list1:
    print ("it is equal to :" ,j)

In [74]:
range(5)

range(0, 5)

In [75]:
list(range(5))

[0, 1, 2, 3, 4]

In [76]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [77]:
list(range(10,100))

[10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

In [78]:
list(range(10,50,5))

[10, 15, 20, 25, 30, 35, 40, 45]

In [79]:
list(range(1,10,3))

[1, 4, 7]

# numpy

In [80]:
import numpy as np
from numpy.random import randn 

In [81]:
randn()

-1.0217052448819315

In [82]:
import random as r
def getotp():
    otp=""
    for i in range(2):
        otp+=str(r.randint(1,5))
        print("your otp is")
        print(otp)    
getotp()

your otp is
5
your otp is
54


In [83]:
import random as r
g=randn()
if g>1:
    ans=" greater than  1"
else :
    ans="less than 1"
print(ans)
print(g)
        

less than 1
0.007505997544325005


In [84]:
list6=[5,50,67,2020]

In [85]:
list6

[5, 50, 67, 2020]

In [86]:
type(list6)

list

In [87]:
list7=[2,3.0,'hi',True,20+5j]

In [88]:
list7

[2, 3.0, 'hi', True, (20+5j)]

In [89]:
type(list7)

list

In [90]:
amx=[11,30,'ame',(3,'good')]
amx

[11, 30, 'ame', (3, 'good')]

In [91]:
fruits=['orange','apple','apple','banana','pear','kiwi','orange','grapes','cherry','banana',]
fruits

['orange',
 'apple',
 'apple',
 'banana',
 'pear',
 'kiwi',
 'orange',
 'grapes',
 'cherry',
 'banana']

In [92]:
len(fruits)

10

In [93]:
fruits.count('apple')

2

In [94]:
fruits.count('banana')

2

In [95]:
range(15)

range(0, 15)

In [96]:
list(range(15))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [97]:
x=[1,2,3,3,4,5,6,7,8,9]
x

[1, 2, 3, 3, 4, 5, 6, 7, 8, 9]

In [98]:
y=range(8)
y

range(0, 8)

In [99]:
list(y)

[0, 1, 2, 3, 4, 5, 6, 7]

In [100]:
list(range(8))

[0, 1, 2, 3, 4, 5, 6, 7]

In [101]:
y=list(range(1,8))
y

[1, 2, 3, 4, 5, 6, 7]

In [102]:
d=list(range(5,8))
d

[5, 6, 7]

In [103]:
d1=list(range(100,120))
d1

[100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119]

In [104]:
d2=list(range(10,20))

In [105]:
d2

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [106]:
d3=list(range(10,20,5))
d3

[10, 15]

In [107]:
d4=list(range(1,5,2))
d4

[1, 3]

In [108]:
d5=list(range(20,40,5))

In [109]:
d5

[20, 25, 30, 35]

In [110]:
v=['a','e','i','o','u']
v

['a', 'e', 'i', 'o', 'u']

In [111]:
v[0]

'a'

In [112]:
v[1]

'e'

In [113]:
v[2]

'i'

In [114]:
v[3]

'o'

In [115]:
v

['a', 'e', 'i', 'o', 'u']

## Reverse Slicing

In [116]:
len(v)

5

In [117]:
v

['a', 'e', 'i', 'o', 'u']

In [118]:
v[4:]

['u']

In [119]:
v[:]

['a', 'e', 'i', 'o', 'u']

In [120]:
v[:3]

['a', 'e', 'i']

In [121]:
v[:-3]

['a', 'e']

In [122]:
v

['a', 'e', 'i', 'o', 'u']

In [123]:
v[4:]

['u']

In [124]:
v[:4]

['a', 'e', 'i', 'o']

In [125]:
v

['a', 'e', 'i', 'o', 'u']

In [126]:
v[0]

'a'

In [127]:
v[::-1]

['u', 'o', 'i', 'e', 'a']

In [128]:
v[0]="rm"
v

['rm', 'e', 'i', 'o', 'u']

In [129]:
rm=['a','b','c','d','e','f','g','h']
rm

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']

In [130]:
rm[4:7]

['e', 'f', 'g']

In [131]:
rm[-6:-2]

['c', 'd', 'e', 'f']

In [132]:
rm

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']

In [133]:
rm[-5:-2]

['d', 'e', 'f']

In [134]:
rm

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']

In [135]:
rm[2:7]

['c', 'd', 'e', 'f', 'g']

In [136]:
rm[-6:-1]

['c', 'd', 'e', 'f', 'g']

In [137]:
rm

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']

In [138]:
rm[0:7:2]

['a', 'c', 'e', 'g']

In [139]:
rm

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']

In [140]:
rm[3:7:3]

['d', 'g']

In [141]:
rm

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']

In [142]:
rm[3:8:2]

['d', 'f', 'h']

In [143]:
bts=['A','B','C','D','E','F','G','H','I','J']
bts

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [144]:
bts[1:3]

['B', 'C']

In [145]:
bts[:]

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [146]:
bts[11]

IndexError: list index out of range

In [147]:
bts

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [148]:
bts[4:]

['E', 'F', 'G', 'H', 'I', 'J']

In [149]:
bts[:4]

['A', 'B', 'C', 'D']

In [150]:
bts

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [151]:
bts[2:4:2]

['C']

In [152]:
bts[2:10:2]

['C', 'E', 'G', 'I']

In [153]:
bts[2:9:2]

['C', 'E', 'G', 'I']

In [154]:
bts[::-1]

['J', 'I', 'H', 'G', 'F', 'E', 'D', 'C', 'B', 'A']

In [155]:
bts[::-3]

['J', 'G', 'D', 'A']

In [156]:
bts

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [157]:
bts[::2]

['A', 'C', 'E', 'G', 'I']

In [158]:
bts

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [163]:
bts[::-2]

['J', 'H', 'F', 'D', 'B']

In [164]:
bts

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [165]:
bts[::-4]

['J', 'F', 'B']

In [166]:
bts[::-3]

['J', 'G', 'D', 'A']

In [167]:
bts

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [168]:
bts[:3]

['A', 'B', 'C']

In [169]:
bts[:-3]

['A', 'B', 'C', 'D', 'E', 'F', 'G']

In [170]:
bts

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [171]:
bts[6:0:-2]

['G', 'E', 'C']

In [172]:
bts

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [173]:
bts[6:2:-2]

['G', 'E']

In [174]:
bts[7:1:-3]

['H', 'E']

## Tuple

In [176]:
t=(10,20,30)

In [177]:
t[1]

20

In [178]:
t[1]=40

TypeError: 'tuple' object does not support item assignment

## Functions in python

In [179]:
range(10,20)

range(10, 20)

In [180]:
list(range(10,20))

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [181]:
list1=list(range(10,20))

In [182]:
list1

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [183]:
len(list1)

10

In [184]:
type(list1)

list

In [185]:
max(list1)

19

In [186]:
min(list1)

10

In [187]:
max(1,254,450)

450

In [188]:
min(1,254,450)

1

## Numpy in python

In [189]:
l=[23245,27,546,215,-1234]
l

[23245, 27, 546, 215, -1234]

In [190]:
type(l)

list

In [191]:
l1=[23245.5,27.8,546.9,215.5,-1234.0,'amx',7.8]
l1

[23245.5, 27.8, 546.9, 215.5, -1234.0, 'amx', 7.8]

In [192]:
import numpy as np

In [194]:
a=np.array(l)
type(a)

numpy.ndarray

In [195]:
l2=[3.0,4.6]
l2

[3.0, 4.6]

In [196]:
a=np.array(l)
a

array([23245,    27,   546,   215, -1234])

In [197]:
b=np.array(l2)
b

array([3. , 4.6])

In [198]:
b=np.array(l2,True)

TypeError: Cannot interpret 'True' as a data type

In [199]:
print(b)

[3.  4.6]


In [200]:
l

[23245, 27, 546, 215, -1234]

In [201]:
l.pop()

-1234

In [202]:
l

[23245, 27, 546, 215]

In [203]:
a

array([23245,    27,   546,   215, -1234])

In [204]:
a.mean()

4559.8

In [205]:
a.mode()

AttributeError: 'numpy.ndarray' object has no attribute 'mode'

In [206]:
a.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [207]:
a

array([23245,    27,   546,   215, -1234])

In [208]:
l

[23245, 27, 546, 215]

In [209]:
l[1:]

[27, 546, 215]

In [210]:
l[0:2]

[23245, 27]

In [211]:
l

[23245, 27, 546, 215]

In [212]:
l[:]

[23245, 27, 546, 215]

In [213]:
l[::2]

[23245, 546]

In [214]:
a

array([23245,    27,   546,   215, -1234])

In [215]:
a[2::]

array([  546,   215, -1234])

In [216]:
a[2:]

array([  546,   215, -1234])

In [217]:
a

array([23245,    27,   546,   215, -1234])

In [218]:
a[2:4]

array([546, 215])

In [219]:
a

array([23245,    27,   546,   215, -1234])

In [220]:
c=a.copy()

In [221]:
c

array([23245,    27,   546,   215, -1234])

In [222]:
a

array([23245,    27,   546,   215, -1234])

In [223]:
a[0]

23245

In [224]:
a

array([23245,    27,   546,   215, -1234])

In [225]:
c

array([23245,    27,   546,   215, -1234])

In [226]:
m=[1,2,3]

In [227]:
m[0]

1

In [228]:
m[0]=81

In [229]:
m

[81, 2, 3]

In [230]:
n=list.copy(m)
n

[81, 2, 3]

In [231]:
n=m.copy()

In [232]:
n

[81, 2, 3]

In [233]:
m

[81, 2, 3]